SQL
Sanerins/tamtam-one-coffee-bot pull request #11
Opened 2023-02-21 21:07 UTC by PaaavelZ

Решено #5

2023-02-21 21:17 UTC, Sanerins commented on LICENSE
> +   5. Submission of Contributions. Unless You explicitly userState otherwise,
Уберсладко зарефачил, конечно)))

2023-02-21 22:21 UTC, Sanerins requested changes
Очень много неклассического, но в принципе +- почти так, как я это и видел)

2023-02-21 22:21 UTC, Sanerins commented on src/main/java/one/coffee/bot/OneCoffeeBotUpdateHandler.java
> +            User user = new User(userId, "Cyberpunk2077", UserState.DEFAULT.getStateId());
Логически неправильное действие.
То, что нам пришло BotStartedUpdate от юзера еще не значит, что это новый юзер.
Это может быть старый юзер, который просто удалил историю переписки с ботом (нам про это никак не сообщается) и снова нажал на кнопку начать

2023-02-21 22:21 UTC, Sanerins commented on src/main/java/one/coffee/sql/tables/UsersTable.java
> +                throw new SQLException("No user with 'userId' = " + userId + " in DB!");
Кидать исключение - это перебор. Можно просто вернуть null и программист сам решит что надо делать. Заставлять его это отлавливать, а потом еще и отпарсивать от других SQLException, которые реально страшные, например БД упала - пытка.
Если есть подобные случаи в других табличках - надо исправить точно

2023-02-21 22:21 UTC, Sanerins commented on src/main/java/one/coffee/sql/tables/UserStatesTable.java
> +                throw new SQLException("No state with 'stateType' = " + stateType);
Опять кидаешь исключение и пытаешь программистов парсингом вместо null)

2023-02-21 22:21 UTC, Sanerins commented on src/main/java/one/coffee/sql/tables/UserStatesTable.java
> +    public static final UserStatesTable INSTANCE = new UserStatesTable();
Это можно вынести в StaticContext для консистентности, сделав сами методы нестатичными

2023-02-21 22:21 UTC, Sanerins commented on src/main/java/one/coffee/sql/tables/UsersTable.java
> +    public static final UsersTable INSTANCE = new UsersTable();
Аналогично можно вынести

2023-02-21 22:21 UTC, Sanerins commented on src/main/java/one/coffee/sql/tables/UserConnectionsTable.java
> +    public static final UserConnectionsTable INSTANCE = new UserConnectionsTable();
Аналогично можно вынести

2023-02-21 22:21 UTC, Sanerins commented on src/main/java/one/coffee/sql/tables/UserConnectionsTable.java
> +                throw new SQLException("User with 'userId' = " + userId + " has not any connections!");
Опять пытаешь бедняг выпаршиванием этого случая вместо возвращения null)

2023-02-21 22:21 UTC, Sanerins commented on src/main/java/one/coffee/bot/OneCoffeeBotUpdateHandler.java
> +            throw new RuntimeException(e);
А вот как раз случай, где нам нужно проверить, что `UsersTable.getUserByUserId(userId);` возвратило не null, и если она возвратила null  - исправить ситуацию и создать запись о юзере.
Сейчас же на каждое его сообщение бот будет молчать, а в логи будет сраться инфа, что такого юзера нет...
Такого быть не должно, поэтому мы и не должны кидать исключение, а просто давать null, вот если реально пипец и лютое SQLException - бд упала, можно и сюда улететь)

2023-02-21 22:21 UTC, Sanerins commented on src/main/java/one/coffee/commands/ChattingCommandHandler.java
> +            LOG.error("The sender " + senderId + " was deleted from DB!"); // TODO Предложения?
Предположения уже были высказаны выше, более того SQLException далеко не только значит, что это просто null прилетел)
Если это просто null - надо создать запись в табличке о юзере - чего уж тут бубнить-то)

2023-02-21 22:33 UTC, Sanerins commented
Кстати раз уж пр рещает #7, то вообще надо не забывать линковать таску с веткой, там это легко очень сделать, заодно сразу и таска потом при мердже закроется сама, и все лейблы будут перенесены автоматом)

2023-02-22 05:18 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/entities/Argument.java
> +public @interface Argument {
В одной из реализаций Entity::sqlArgValues я оставил комментарий о том, что такая аннотация в перспективе поможет убрать дублирующийся код у всех реализаций, поскольку по сути чтобы дать все значения таблички, нам надо просто иметь набор полей этой таблички, а его можно получить по этой аннотации.

2023-02-22 05:18 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/utils/Utils.java
> +public class Utils {
Почему-то казалось, что у контекста функциональное значение другое. Окей, объединю.

2023-02-22 05:23 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/DB.java
> +// TODO Решить проблему SQL-инъекций.
В базу стринги закладываются квотированными, а из неё достаются в обычном виде. В этой ситуации, если юзер сохранил в качестве того же города SQL инъекцию, то она может примениться, когда мы снова полезем в базу. Напишу тест на это.

2023-02-22 08:53 UTC, Sanerins commented on src/main/java/one/coffee/sql/utils/Utils.java
> +public class Utils {
Насчёт конкретно этого лучше ещё посмотреть и обсудить.
Если эти константы используются только для парсинга классов в SQL, то возможно стоит действительно выделить их в отдельный класс, названный SqlUtils, чтобы работяги на эти константы и не смотрели лишний раз, а только когда они им действительно понадобятся

2023-02-22 11:11 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/utils/Utils.java
> +public class Utils {
Да, они только для парсинга используются. Я думал назвать их SqlUtils, но показалось, что их расположение должно говорить само за себя.

2023-02-22 12:37 UTC, Sanerins commented on src/main/java/one/coffee/sql/utils/Utils.java
> +public class Utils {
Просто проблема в том, что в большом проекте ты ищешь файлы просто используя фичу поиска по проекту, не щёлкая вручную по пакетам, ибо их там 100+ штук, ну и при просмотре кода программист в первую очередь видит только название класса, а не импорт который там в облаках, в самом начале)
По этой причине все названия файлов всегда должны быть очевидными сами по себе, иначе начинается путаница, которую можно было бы избежать

2023-02-22 12:55 UTC, PaaavelZ commented on LICENSE
> +   5. Submission of Contributions. Unless You explicitly userState otherwise,
Случайно. Исправил.

2023-02-22 13:17 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/entities/User.java
> +    public User(long id, long userId, String city, long stateId, long connectionId) throws SQLException {
Согласен, исправил во всех сущностях.

2023-02-23 19:07 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/utils/Utils.java
> +public class Utils {
Решил всё же оставить SQLUtils, но в них лишь константы, а инстансы таблиц поместил в StaticContext - так кажется правильней с функциональной точки зрения.

2023-02-23 19:08 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/tables/UsersTable.java
> +                Map.entry("userId", "BIGINT"),
Да, тоже так думал, заоверинженирил

2023-02-23 19:09 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/entities/UserState.java
> +        UserStatesTable.putUserState(this);
Не согласен. Может с точки зрения SingleResponsibility это не айс, но метод крутой, прокся очень удобная и интуитивно понятная. Раз User, то и коммит будет в UsersTable, чтобы сохранить юзера.

2023-02-23 19:10 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/entities/User.java
> +        // TODO Оптимизировать, чтобы ручками не вводить каждый аргумент. Сделать список из аннотированных элементов @Argument
Убрал.

2023-02-23 19:10 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/DB.java
> +// TODO Решить проблему SQL-инъекций.
Тест на инъекции откладывается на другое MVP.

2023-02-23 19:12 UTC, PaaavelZ commented on src/main/java/one/coffee/bot/OneCoffeeBotUpdateHandler.java
> +            User user = new User(userId, "Cyberpunk2077", UserState.DEFAULT.getStateId());
Ну раз нажал на кнопку **"Начать"**, то и состояние у него **DEFAULT**. Что неправильного?

2023-02-23 19:14 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/tables/UsersTable.java
> +                throw new SQLException("No user with 'userId' = " + userId + " in DB!");
На этапе парсинга значений согласен. А что делать на этапе создания объекта? Нам в юзера закинули отрицательный айди в конструктор, и как на это реагировать?

2023-02-23 19:14 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/tables/UserStatesTable.java
> +    public static final UserStatesTable INSTANCE = new UserStatesTable();
Сделано.

2023-02-23 19:16 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/tables/UserConnectionsTable.java
> +                throw new SQLException("User with 'userId' = " + userId + " has not any connections!");
Исправил.

2023-02-23 19:18 UTC, PaaavelZ commented on src/main/java/one/coffee/bot/OneCoffeeBotUpdateHandler.java
> +            throw new RuntimeException(e);
А как мы тут заново соберём юзера? Нам доступно только его айди, ни города, ни описания мы извлечь ниоткуда не можем, раз база пустая.

2023-02-23 19:19 UTC, PaaavelZ commented on src/main/java/one/coffee/bot/OneCoffeeBotUpdateHandler.java
> +            throw new RuntimeException(e);
В теории можно кнш тут завести диалог с пользователем, мол, работяга, войди в положение, база пустая, инфа твоя потерялась, дай новую, но это не кринжатина разве?

2023-02-23 20:04 UTC, PaaavelZ commented on src/main/java/one/coffee/commands/ChattingCommandHandler.java
> +            LOG.error("The sender " + senderId + " was deleted from DB!"); // TODO Предложения?
Расписал в коде возможные причины исключения и свои мысли на этот счёт.

2023-02-23 20:39 UTC, PaaavelZ commented
> Очень много неклассического, но в принципе +- почти так, как я это и видел)

Исправил все замечания, в коде расписал причины ошибок и null'ов и что с этим можно сделать, ещё остаётся, что обсудить.

2023-02-23 20:44 UTC, Sanerins commented on src/main/java/one/coffee/bot/OneCoffeeBotUpdateHandler.java
> +            throw new RuntimeException(e);
Ну на текущем этапе просто дефолтную инфу хотя бы прописать, как у тебя с киберпанком при старте бота)))
Ну а в дальнейшем да, тип присылать сообщение мол "Судя по всему у вас не создан профиль в боте. Сойдайте и заполните его такими-то командами"
Ну а тип че нам еще остается делать, не оставлять же юзера без профиля

2023-02-23 20:46 UTC, Sanerins commented on src/main/java/one/coffee/sql/entities/UserState.java
> +        UserStatesTable.putUserState(this);
Так может у нас будет несколько Table в дальнейшем, которые принимают DAO юзера, и тогда будет совершенно неочевидно куда этот метод нас кидает

2023-02-23 20:55 UTC, Sanerins commented on src/main/java/one/coffee/bot/OneCoffeeBotUpdateHandler.java
> +            User user = new User(userId, "Cyberpunk2077", UserState.DEFAULT.getStateId());
В твоей старой версии кода был бы дубликат)
Так как ты передавал userId только, а еще был другой id. По логике твоего старого кода если ты не передавал два id, значит надо создавать новую запись в табличке, если бы передал - искалась бы старая

2023-02-23 20:58 UTC, Sanerins commented on src/main/java/one/coffee/sql/tables/UsersTable.java
> +                throw new SQLException("No user with 'userId' = " + userId + " in DB!");
В конструкторе самого DAO (т.е Entity) - никак. Это просто хранилище инфы, там может быть что угодно.
На моменте, когда мы вызываем метод putUser и аналогичные ему, будет уместно проверять поля DAO, что нам передали, и кидать IllegalArgumentException, если есть нарушения по типу отрацательного ID

2023-02-23 21:25 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/tables/UsersTable.java
> +                throw new SQLException("No user with 'userId' = " + userId + " in DB!");
Ну так давай сразу кидать исключение, если есть ошибка, надо о ней сразу сообщить прямо в конструкторе

2023-02-23 21:39 UTC, Sanerins requested changes
Много проблем с пониманием сути сущностей DAO и их назначения, в остальном стало сильно слаще)

2023-02-23 21:39 UTC, Sanerins commented on src/main/java/one/coffee/utils/CommandHandler.java
> +    // TODO /text не работает, на самом деле, в чате нельзя на него нажать. Надо это пофиксить.
Какой еще `/text`?
`handleText` означает, что юзер прислал нам простой текст, вместо команды, это видно из метода `handle` выше. Т.е это логика на случай, когда юзер прислал нам 'Привет!', например

2023-02-23 21:39 UTC, Sanerins commented on src/main/java/one/coffee/sql/tables/UsersTable.java
> +                LOG.warn("No user with 'id' = {} in DB!", userId);
Не уверен, что это надо логировать, особенно на уровне `warn`.
Программист вообще может написать код аля
```
if (UsersTable.getUserByUserId(12345L) == null) {
//do smth
}
```
И мы тут вообще ожидаем по логике, что нам прийдет null, поэтому забивать логгер таким не особо надо. Если null точно не должен быть, а он пришел - то проггер сам это залогирует

2023-02-23 21:39 UTC, Sanerins commented on src/main/java/one/coffee/sql/tables/UserConnectionsTable.java
> +                LOG.warn("User with 'id' = {} has not any connections!", userId);
Аналогично с Users

2023-02-23 21:39 UTC, Sanerins commented on src/main/java/one/coffee/sql/entities/UserState.java
> +            if (userState.ordinal() == id) {
Мне кажется лучше сделать, чтобы просто у enum было поле интовое с id
```
private enum DownloadType {
    AUDIO(0), VIDEO(1), AUDIO_AND_VIDEO(2);
    private final int value;

    private DownloadType(int value) {
        this.value = value;
    }
}
```

Условно так. При таком подходе будет более очевидно, что порядок Enum важен, а сейчас программист может не думая добавить новыц стейт сверху, а не снизу, и это похерит нахрен всю бизнес-логику

2023-02-23 21:39 UTC, Sanerins commented on src/main/java/one/coffee/sql/DB.java
> +            throw new RuntimeException("DB creation is failed! Details: " + e.getMessage());
Приложение не положится)))))))
Бот умный и ловит все ошибки, логируя их, как раз чтобы внезапная ошибка не повалила его на проде, отключать его надо не по-варварсики
Для этого у OneCoffeeBot есть метод `stop();`
Поэтому тут надо сначала логгером залогировать, а потом прописать `bot.stop()`. Для таких случаев можно добавить переменную с ним в `StaticContext`

2023-02-23 21:39 UTC, Sanerins commented on src/main/java/one/coffee/bot/OneCoffeeBotUpdateHandler.java
> +                // 2. Невалидный запрос (на любой стадии).
При невалидном запросе (если имеется ввиду, что он невалидный в плане программист передал кринжатину через DAO) надо будет кидать IllegalArgumentException.
Ибо передал невалидные данные, так как недосмотрел и передал валидные данные и ничего не нашли - это очень разные по логики случаи

2023-02-23 21:39 UTC, Sanerins commented on src/main/java/one/coffee/sql/entities/User.java
> +            throw new IllegalArgumentException("Invalid User id! Got " + userId);
Обычно такие проверки делают на моменте уже коммита, а не на моменте создания самого DAO
Более того проверку с городом вообще можно обойти, потому что `setCity` такой метод не вызывает))
Обычно делают на моменте коммита в базу - так как сейчас нет особого смысла проверять, само создание такого класса никакого нарушения не сделало. Нарушение будет когда программист начнет его коммитить с плохими полями, ну тогда мы ему и кинем IllegalArgument. Так как возможно программист условно будет собирать инфу по кусочкам перед коммитом - сначала создаст DAO, у которого все поля тупо null, а потом будет потихоньку их заполнять, получая информацию от пользователя шаг за шагом (например актуально для этапа регистрации - создаем сначала пустую оболочку, начинаем ее заполнять путем спрашивания вопроса - получения ответа. Мол сначала какой город, потом какой пол, потом какое описание, потом какие увлечения и так далее). По итогу получится валидный User, хоть изначально его создали пустышкой

2023-02-23 21:39 UTC, Sanerins commented on src/main/java/one/coffee/sql/entities/UserConnection.java
> +        if (isDestructed) {
Опять лишняя логика в `DAO`. 
Более того, эта инфа могла уже устареть сотню лет назад, то, что мы не разрушили здесь соединение еще не значит, что кто-то другой его не разрушил. Эта проверка вообще ничего нам не дает, просто дает лишнее чувство ложной защищенности

2023-02-23 21:39 UTC, Sanerins commented on src/main/java/one/coffee/sql/entities/UserConnection.java
> +        if (isCommitted) {
Опять лишняя логика в `DAO`. 
Более того, эта инфа могла уже устареть сотню лет назад, то, что мы не создавали здесь соединение еще не значит, что кто-то другой его не создал. Эта проверка вообще ничего нам не дает, просто дает лишнее чувство ложной защищенности.

2023-02-23 21:39 UTC, Sanerins commented on src/main/java/one/coffee/sql/entities/UserConnection.java
> +    private void commitUsersConnection(long connectionId, UserState state) throws SQLException {
Мне кажется это просто должно быть методом в `UserConnectionsTable`
Вообще не понял зачем это здесь

2023-02-23 21:39 UTC, Sanerins commented on src/main/java/one/coffee/sql/entities/UserConnection.java
> +            throw new IllegalArgumentException(user1 + " or " + user2 + " has already connected!");
Опять лишняя инфа в DAO. Чел когда сам создает DAO может писать там че захочет, если он потом закоммитит херню - мы ему дадим исключение.
Если же он запросит инфу о коннекшене - он это сделает через USER_CONNECTIONS_TABLE, и она ему сама вся правильно заполнит используя свою бизнес-логику, а не бизнес-логику консруктора DAO

2023-02-23 21:39 UTC, Sanerins commented on src/main/java/one/coffee/sql/entities/UserConnection.java
> +        this.id = UserConnectionsTable.getUserConnectionUserById(user1Id).getId();
Про эту проблему я уже расписал в топике про User - перенос логики таблицы на `DAO` по непонятной причине

2023-02-24 05:36 UTC, PaaavelZ commented on src/main/java/one/coffee/utils/CommandHandler.java
> +    // TODO /text не работает, на самом деле, в чате нельзя на него нажать. Надо это пофиксить.
Блин, сори, /help не жмякается, когда тут ошибка вылетает, насколько я помню

2023-02-24 05:39 UTC, PaaavelZ commented on src/main/java/one/coffee/bot/OneCoffeeBotUpdateHandler.java
> +                // 2. Невалидный запрос (на любой стадии).
Невалидный в плане SELECT nonExistentColumn FROM nonExistentTable

2023-03-08 18:34 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/tables/UsersTable.java
> +                LOG.warn("No user with 'id' = {} in DB!", userId);
Почистил все такие моменты, справедливо

2023-03-08 18:35 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/entities/UserState.java
> +            if (userState.ordinal() == id) {
Сделано

2023-03-08 18:37 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/DB.java
> +            throw new RuntimeException("DB creation is failed! Details: " + e.getMessage());
Пофиксил

2023-03-08 18:37 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/entities/User.java
> +            throw new IllegalArgumentException("Invalid User id! Got " + userId);
Да, сейчас логика совсем другая, этого уже нет

2023-03-08 18:49 UTC, PaaavelZ commented
> Много проблем с пониманием сути сущностей DAO и их назначения, в остальном стало сильно слаще)

Полностью переписал архитектуру, решил те проблемы, что были на предыдущих ревью. Добавил новых тудушек в код, просьба ознакомиться и с тестами, ибо они показывают, какую логику в каких ситуациях мы ожидаем встретить.

2023-03-19 14:10 UTC, coradead commented on src/main/java/one/coffee/utils/CommandHandler.java
> +    // TODO /text не работает, на самом деле, в чате нельзя на него нажать. Надо это пофиксить.
Так может удалить коммент?

2023-03-19 14:15 UTC, coradead commented on src/main/java/one/coffee/utils/CommandHandler.java
> +        );
Кажется что-то, что выше и это - одно и тоже. Наверное лучше обрабатывать "не команды" в одном месте, а не отдельно в one.coffee.utils.CommandHandler.handle и one.coffee.commands.DefaultCommandHandler.handleCommand (это как пример). Для этого в CommandHandler можно объявить commandList (мапа с названием команды и хендлером), а внутри one.coffee.utils.CommandHandler.handle смотреть если такая команда в этом commandList. Таким образом у нас проверка на неправильные команды будет в 1 месте.

2023-03-19 14:23 UTC, coradead commented on src/main/java/one/coffee/utils/CommandHandler.java
> +        );
Сейчас посмотрел еще - это всетаки разные вещи, но все равно неправлиьные команды бы хотелось бы отсеивать в одном месте, к тому же это избавит нас от one.coffee.utils.CommandHandler.handleCommand

2023-03-19 14:25 UTC, coradead commented on src/main/java/one/coffee/commands/ChattingCommandHandler.java
> +                NewMessageBodyBuilder.ofText("Пользователь решил закончить с вами диалог, надеюсь все прошло сладко!").build()
Скорее уж собеседник

2023-03-19 14:31 UTC, coradead commented on src/main/java/one/coffee/commands/ChattingCommandHandler.java
> +        if (optionalRecipient.isEmpty()) { // TODO Восстановление инфы
Что за восстановление?

2023-03-19 14:36 UTC, coradead commented on src/main/java/one/coffee/sql/user_connection/UserConnectionService.java
> +        userConnectionDao.delete(userConnection);
Эти 2 строки должны быть в одной транзакции, вместе, иначе неконсистентность

2023-03-19 14:53 UTC, PaaavelZ commented on src/main/java/one/coffee/bot/OneCoffeeBotUpdateHandler.java
> +        User user = new User(userId, "Cyberpunk2077", UserState.DEFAULT);
Если переедет, то должен нам об этом сказать, потом будет фича изменить свои данные, чтобы бот корректно искал ему собеседника. А вообще бот предполагает некоторую статичность геолокации пользователей, ожидается, что человек, ищущий собеседника, не переедет завтра, а если и переедет, то только к своему собеседнику, которого мы ему и найдем) В таком кейсе, кстати, пользователь может указывать разные города и искать в них единомышленников, но все же наиболее частым будет кейс поиска людей, находящихся в том же городе, что и ты.

2023-03-19 14:58 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/user/UserDao.java
> +                getInstance().getShortName()
Блин, думал, многострочные строки - это удел питона. Согласен,  исправлю.

2023-03-19 15:00 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/user_connection/UserConnectionDao.java
> +        return Optional.ofNullable(userConnection.get());
Неправда, у меня DB.execute не в многопотоке исполняется, поэтому в текущей реализации нормально. Вот как сделает кто-то многопоток, так ему и надо будет над этим запариваться, чтобы фьючеры отправлять и так далее.

2023-03-19 15:13 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/Dao.java
> +    abstract public void save(T t);
Звучит резонно, порефачу.

2023-03-19 15:16 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/DB.java
> +            STATEMENT.execute(query);
1. Какой еще такой `executeUpdate()`? Не видел такого метода в базе;
2. В будущем я планировал возвращать флажки состояния, ок или не ок, где-то даже в коде писал об этом, но это не сейчас, да.

2023-03-19 15:17 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/DB.java
> +                + " VALUES " + entity.sqlArgValues());
Это сделает -1 поход в базу во время создания энтити, чтобы не разбираться, какое айди ей было назначено. Или ты что-то еще подразумевал?

2023-03-19 15:19 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/DB.java
> +            STATEMENT = CONNECTION.createStatement();
1. Сделаю Closeable - пойдет?
2. Почему кажется?
3. А почему нет? Есть тесты на многопоток, нас результаты устраивают.

2023-03-19 15:19 UTC, PaaavelZ commented on src/main/java/one/coffee/bot/OneCoffeeBotUpdateHandler.java
> +            case CHATTING -> chattingHandler.handle(update.getMessage());
Да, звучит круто.

2023-03-19 15:21 UTC, PaaavelZ commented on src/main/java/one/coffee/bot/OneCoffeeBotUpdateHandler.java
>                          NewMessageBodyBuilder.ofText("Оххх... Что-то ошибочка вышла... Попробуйте еще раз").build());
? Предлагаешь вынести все тексты в константы? Зачем? Повторов я еще не видел, если есть, то это какой-то дефолтный текст по типу "Произошла ошибка". Его можно вынести, а вот другие зачем? Цикл разработки усложнится как-то, если не вынести?

2023-03-19 15:22 UTC, PaaavelZ commented
> Так может удалишь коммент?
Зачем удалять? Я указал на неверное поведение в коде, это не моя зона ответственности, ее другой человек должен будет исправить.

2023-03-19 15:24 UTC, PaaavelZ commented on src/main/java/one/coffee/utils/CommandHandler.java
> +        );
Возьму на заметку идеи с мапами, мне нравится.

2023-03-19 15:25 UTC, PaaavelZ commented on src/main/java/one/coffee/commands/ChattingCommandHandler.java
> +                NewMessageBodyBuilder.ofText("Пользователь решил закончить с вами диалог, надеюсь все прошло сладко!").build()
Чел))))))

2023-03-19 15:25 UTC, PaaavelZ commented on src/main/java/one/coffee/commands/ChattingCommandHandler.java
> +                NewMessageBodyBuilder.ofText("Пользователь решил закончить с вами диалог, надеюсь все прошло сладко!").build()
Чел))))))

2023-03-19 15:26 UTC, PaaavelZ commented on src/main/java/one/coffee/commands/ChattingCommandHandler.java
> +        if (optionalRecipient.isEmpty()) { // TODO Восстановление инфы
Ну мы потеряли собеседника нашего юзера, нужно что-то предпринять, как-то восстановить данные о нем (например, если мы юзеру до этого давали инсайды о его собеседнике, то он сможет нам помочь разыскать его).

2023-03-19 15:28 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/user_connection/UserConnectionService.java
> +        userConnectionDao.delete(userConnection);
Есть идеи, как это сделать в рамках текущей архитектуры?

2023-03-19 15:31 UTC, coradead commented on src/main/java/one/coffee/bot/OneCoffeeBotUpdateHandler.java
> +        User user = new User(userId, "Cyberpunk2077", UserState.DEFAULT);
Кажется, что если ты долго живешь в городе, то и искать друзей не надо)

2023-03-19 15:31 UTC, PaaavelZ commented
> На самом деле если бы я принимал больше участия - я бы настоял на некоторых архитектурных вопросах, но так как я сам виноват - ничего не имею против. В целом я вообще не смотрел сообщения, которые отправляются людям - я бы сделал хотябы класс с гигантской мапой, где будут храниться ключ и текст сообщения, но возможно это сомнительно. Я больше смотрел на код, чем архитектурные вопросы

1. А что бы архитектурно ты мог бы предложить? Мне как разработчику интересно;
2. Ну рапу для сообщений кринжово создавать, вспомни, как мы на Андроидах делали - там были крутые понятные константы текстовые, которые все юзали. Я вот думаю о чем-то таком, но у этого пока нет юзабельности в проекте, тексты почти нигде не дублируются, поэтому норм пока иметь такие "магические строки".

2023-03-19 15:31 UTC, coradead commented on src/main/java/one/coffee/sql/user_connection/UserConnectionDao.java
> +        return Optional.ofNullable(userConnection.get());
Тогда зачем атомики?

2023-03-19 15:32 UTC, coradead commented on src/main/java/one/coffee/sql/DB.java
> +            STATEMENT.execute(query);
по 1му пункту - чек 
<img width="971" alt="image" src="https://user-images.githubusercontent.com/50422378/226186746-882259ba-b42a-49d4-8ed4-40d671d438c9.png">

2023-03-19 15:34 UTC, coradead commented on src/main/java/one/coffee/sql/DB.java
> +                + " VALUES " + entity.sqlArgValues());
Количество походов не изменится, просто мы сказу можем записать id

2023-03-19 15:35 UTC, PaaavelZ commented on src/main/java/one/coffee/bot/OneCoffeeBotUpdateHandler.java
> +        User user = new User(userId, "Cyberpunk2077", UserState.DEFAULT);
Чел, че за кринжатину ты щас говоришь, некоторые люди меняются, из состояния социолога переходят в состояние открытости, кто-то теряет близких, кто-то хочет перейти через себя. Есть куча причин, почему человек, долго живущий в одном городе, ищет в нем друзей, даже самые банальные.

2023-03-19 15:36 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/user_connection/UserConnectionDao.java
> +        return Optional.ofNullable(userConnection.get());
Потому что лямбду юзаю для запроса к базе, лямбды требуют атомиков.

2023-03-19 15:36 UTC, coradead commented on src/main/java/one/coffee/sql/DB.java
> +            STATEMENT = CONNECTION.createStatement();
1 нет нужны try with resources 
2 потому что я супер плотно не смотрел в реализацию, но комментарии говорят, что здесь он нужен
3 там многопотока не должно быть) судя по доке, а по поводу того, что statement один - это кажется супер странным - у тебя куча запросов, но 1 стейтмент

2023-03-19 15:37 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/DB.java
> +            STATEMENT.execute(query);
Какой чек?

2023-03-19 15:37 UTC, coradead commented on src/main/java/one/coffee/bot/OneCoffeeBotUpdateHandler.java
>                          NewMessageBodyBuilder.ofText("Оххх... Что-то ошибочка вышла... Попробуйте еще раз").build());
Все константы должны быть static final. Всегда

2023-03-19 15:38 UTC, coradead commented on src/main/java/one/coffee/commands/ChattingCommandHandler.java
> +        if (optionalRecipient.isEmpty()) { // TODO Восстановление инфы
звучит супер странно, но ладно

2023-03-19 15:39 UTC, coradead commented on src/main/java/one/coffee/sql/user_connection/UserConnectionService.java
> +        userConnectionDao.delete(userConnection);
Ну jdbc предоставляет нам такие возможности) гугл в помощь

2023-03-19 15:40 UTC, coradead commented
> > Так может удалишь коммент?
> 
> Зачем удалять? Я указал на неверное поведение в коде, это не моя зона ответственности, ее другой человек должен будет исправить.

так он не корректный и в конце концов заведи issue, но не коммент в коде

2023-03-19 15:41 UTC, coradead commented
> > На самом деле если бы я принимал больше участия - я бы настоял на некоторых архитектурных вопросах, но так как я сам виноват - ничего не имею против. В целом я вообще не смотрел сообщения, которые отправляются людям - я бы сделал хотябы класс с гигантской мапой, где будут храниться ключ и текст сообщения, но возможно это сомнительно. Я больше смотрел на код, чем архитектурные вопросы
> 
> 1. А что бы архитектурно ты мог бы предложить? Мне как разработчику интересно;
> 2. Ну мапу для сообщений кринжово создавать, вспомни, как мы на Андроидах делали - там были крутые понятные константы текстовые, которые все юзали. Я вот думаю о чем-то таком, но у этого пока нет юзабельности в проекте, тексты почти нигде не дублируются, поэтому норм пока иметь такие "магические строки".

1 какниюудь очно расскажу
2 тут смысл не в дублировании, а в центролизованости - ты сразу видишь все сообщения, которые отдаются юзеру и в случае чего - не надо рыться во всех папках

2023-03-19 15:53 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/DB.java
> +            STATEMENT.execute(query);
1. Почему "скорее"? Чем обычный `execute()` не нравится?

2023-03-26 12:21 UTC, artem24630 commented on src/main/java/one/coffee/sql/user_connection/UserConnectionService.java
> +    public static UserConnectionService getInstance() {
почему не заюзать спринг хотя бы для DI?

2023-03-26 12:21 UTC, artem24630 commented on src/main/java/one/coffee/utils/MessageSender.java
> +        if (messageBody.getText() == null || messageBody.getText().length() <= 4000) { // 4000 - max characters in message text
4к - это ограничение там тама или мы сами придумали?

2023-03-26 12:21 UTC, artem24630 commented on src/main/java/one/coffee/bot/OneCoffeeBotUpdateHandler.java
> +            case CHATTING -> chattingHandler.handle(update.getMessage());
В чем проблема засунуть в UserState эти обработчики, тогда не нужно будет ни свичи, ни мапы

2023-03-26 12:52 UTC, PaaavelZ commented on src/main/java/one/coffee/utils/MessageSender.java
> +        if (messageBody.getText() == null || messageBody.getText().length() <= 4000) { // 4000 - max characters in message text
@Sanerins

2023-03-26 12:52 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/user_connection/UserConnectionService.java
> +    public static UserConnectionService getInstance() {
Что такое DI?

2023-03-26 12:52 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/user/UserService.java
> +    private static final Logger LOG = LoggerFactory.getLogger(MethodHandles.lookup().lookupClass());
Копипаста кода. @Sanerins

2023-03-26 12:54 UTC, PaaavelZ commented on src/main/java/one/coffee/bot/OneCoffeeBotUpdateHandler.java
> +            case CHATTING -> chattingHandler.handle(update.getMessage());
Нарушение Single Responsobility - UserState у нас dto, оно бизнес-логику исполнять не должно.

2023-03-26 12:55 UTC, PaaavelZ commented on src/main/java/one/coffee/commands/ChattingCommandHandler.java
> +        if (optionalRecipient.isEmpty()) { // TODO Восстановление инфы
@Sanerins

2023-03-28 15:38 UTC, Sanerins commented on src/main/java/one/coffee/sql/user_connection/UserConnectionService.java
> +    public static UserConnectionService getInstance() {
Dependency Injection (@Autowired)
Потому что мне показалось, что такую большую зависимость подрубать и настраивать, чтобы она адекватно работала ради одного единственного юзкейса - перебор. В принципе static context, который я изначально сделал, +- собой и заменяет Dependency Injection для приложения нашего масштаба (маленького), но при этом в разы меньше по размеру и работает более очевидно, а лютый специалистов по спрингу среди нас нет, чтобы решать с ним вопросы, если появятся

2023-03-28 15:41 UTC, Sanerins commented on src/main/java/one/coffee/utils/MessageSender.java
> +        if (messageBody.getText() == null || messageBody.getText().length() <= 4000) { // 4000 - max characters in message text
Ограничение ТамТама, чтобы не делилось на два сообщения сразу. Этот код взят из ПР в мастер из репы SDK

2023-03-28 15:45 UTC, Sanerins commented on src/main/java/one/coffee/commands/ChattingCommandHandler.java
> +        if (optionalRecipient.isEmpty()) { // TODO Восстановление инфы
Вообще я даже не это восстановление инфы имел ввиду, а хотя бы просто вернуть юзера в дефолтное состояние и испраивить нашу ошибку. Короче вопрос в том, что если нам пришел нулл, то надо чета с этим сделать, иначе юзер будет бесконечно пытаться отправить сообщение, и мы каждый раз будем ловить налл и ничего с ним не делать. Как минимум вернуть несчастного отправителя сообщений, получатель которых пропал из бд, в дефолтное состояние и написать что-то по типу "Ой! Собеседник потерялся..."

2023-03-29 08:02 UTC, artem24630 approved these changes

2023-03-29 08:02 UTC, merged