issue-6 add /stop
Sanerins/tamtam-one-coffee-bot pull request #12
Opened 2023-04-15 13:29 UTC by artem24630

2023-04-15 13:52 UTC, PaaavelZ requested changes

2023-04-15 13:52 UTC, PaaavelZ commented on src/main/java/one/coffee/commands/WaitingCommandHandler.java
> +            case "/stop" -> {
1) А что будет в случае `default`?
2) A если len(commandWithArgs) > 1?

2023-04-15 13:52 UTC, PaaavelZ commented on src/main/java/one/coffee/commands/ChattingCommandHandler.java
> +        Optional<User> senderOpt = userService.get(userConnection.getUser1Id());
В конекшене юзеры не упорядочены по "отправителю" - "получателю", ты не знаешь, кто такой `user1`. У тебя же есть `senderId` выше по коду, возьми его.

2023-04-15 13:52 UTC, PaaavelZ commented on src/main/java/one/coffee/commands/ChattingCommandHandler.java
> +        if (senderOpt.isEmpty()) {
Если сендера нет, но на 68 строчке вылетит исключение, по-моему. То есть проверка тут не нужна

2023-04-15 13:52 UTC, PaaavelZ commented on src/main/java/one/coffee/commands/ChattingCommandHandler.java
> +        recipient.setState(UserState.DEFAULT);
Если сендер сбросил трубку и больше не хочет ни с кем общаться, это не означает, что реципиент придерживается такой же позиции.

2023-04-15 13:52 UTC, PaaavelZ commented on src/main/java/one/coffee/commands/WaitingCommandHandler.java
>  //TODO: по методу handle вполне понятно что надо сделать)
туду удали тогда, раз сделал

2023-04-15 13:52 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/user/UserDao.java
> +                        " ORDER BY RANDOM()" +
А это зачем?

2023-04-15 13:52 UTC, PaaavelZ commented on src/main/java/one/coffee/utils/CommandHandler.java
> +        if (StringUtil.isEmpty(text) || text.charAt(0) != '/') {
Не одобряю такой фикс, ты подключил целую библу ради одной утилитной функции

2023-04-15 13:58 UTC, artem24630 commented on src/main/java/one/coffee/commands/ChattingCommandHandler.java
> +        recipient.setState(UserState.DEFAULT);
так же не означает, что он хочет с кем-то общаться еще

2023-04-15 13:59 UTC, artem24630 commented on src/main/java/one/coffee/sql/user/UserDao.java
> +                        " ORDER BY RANDOM()" +
так как у нас random coffee

2023-04-15 14:05 UTC, PaaavelZ commented on src/main/java/one/coffee/commands/ChattingCommandHandler.java
> +        recipient.setState(UserState.DEFAULT);
ну он не отправил никакой явной команды об этом -> считаем, что его состояние WAITING

2023-04-15 14:05 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/user/UserDao.java
> +                        " ORDER BY RANDOM()" +
и что?

2023-04-15 14:10 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/user/UserDao.java
> +                        " ORDER BY RANDOM()" +
приведи мне кейс, когда только что разведенных пользователей сконнектит снова?

2023-04-15 14:13 UTC, artem24630 commented on src/main/java/one/coffee/sql/user/UserDao.java
> +                        " ORDER BY RANDOM()" +
всегда

2023-04-15 14:16 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/user/UserDao.java
> +                        " ORDER BY RANDOM()" +
почему?

2023-04-15 14:17 UTC, PaaavelZ commented on src/main/java/one/coffee/sql/user/UserDao.java
> +                        " ORDER BY RANDOM()" +
вообще мы по коду используем вызов `getWaitingUsers(n=1)`, так что твой `ORDER BY RANDOM` ничего не решает.

2023-04-17 17:52 UTC, PaaavelZ approved these changes

2023-04-17 17:52 UTC, merged